# cloud configurations
spring:
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: service1
#                fallbackuri: forward:/service1FallBack
        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: service2
#                fallbackuri: forward:/service2FallBack
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

